name: MinemuPrincipales
version: '${project.version}'
main: es.minemu.minemuprincipales.MinemuPrincipales
api-version: '1.20'
folia-supported: true
author: Javier

commands:
  saludo:
    description: Saluda al servidor
    usage: /saludo
  curar:
    description: Restaura la salud del jugador al máximo
    usage: /curar
  teleport:
    description: Teletransporta al jugador a coordenadas específicas
    usage: /teleport <x> <y> <z>
  fly:
    description: Activa o desactiva el modo de vuelo del jugador
    usage: /fly
  sethome:
    description: Establece la ubicación de inicio personalizada del jugador
    usage: /sethome
  home:
    description: Teletransporta al jugador a su ubicación de inicio personalizada
    usage: /home
  tpa:
    description: Solicita una solicitud de teletransporte a otro jugador
    usage: /tpa <jugador>
  tpaccept:
    description: Acepta una solicitud de teletransporte pendiente
    usage: /tpaccept
  tpall:
    description: Teletransporta a todos los jugadores a tu ubicación
    usage: /tpall
  broadcast:
    description: Envía un mensaje a todo el servidor
    usage: /broadcast <mensaje>
  heal:
    description: Restaura la salud del jugador al máximo
    usage: /heal
  setspawn:
    description: Establece el punto de aparición predeterminado del mundo
    usage: /setspawn
  workbench:
    description: Abre un banco de trabajo para el jugador
    usage: /workbench
  nick:
    description: Cambia el nombre visible del jugador
    usage: /nick <nombre>
  timeleft:
    description: Muestra el tiempo restante hasta el próximo día
    usage: /timeleft
  weatherclear:
    description: Limpia el clima y establece el tiempo en claro
    usage: /weatherclear
  feed:
    description: Rellena la barra de hambre del jugador
    usage: /feed
  gm:
    description: Cambia el modo de juego del jugador (solo para jugadores con permisos)
    usage: /gm <modo>
  spawn:
    description: Teletransporta al jugador al punto de aparición del mundo
    usage: /spawn
  setwarp:
    description: Establece una ubicación de warp en el mundo
    usage: /setwarp <nombre>
  warp:
    description: Teletransporta al jugador a una ubicación de warp previamente establecida
    usage: /warp <nombre>
  vanish:
    description: Activa o desactiva el modo invisible del jugador
    usage: /vanish
  pet:
    description: Permite a los jugadores obtener una mascota
    usage: /pet <tipo>
  petlist:
    description: Muestra la lista de mascotas del jugador
    usage: /petlist
  petrename:
    description: Cambia el nombre de una mascota
    usage: /petrename <nuevo_nombre>
  petrelease:
    description: Libera a una mascota
    usage: /petrelease
  god:
    description: Modo dios
    usage: /god
  petcall:
    description: Llama a la mascota
    usage: /petcall
  ayuda:
    description: ayuda de commandos
    usage: /ayuda


permissions:
  MinemuPrincipal.vanish:
    default: op
  MinemuPrincipal.gm:
    default: op
  MinemuPrincipal.god:
    default: op
